spring: 
 h2:
  console:
   enabled: true
   path: /console
   settings:
    web-allow-others: true
 datasource:
  url: jdbc:h2:mem:salesga;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=END,USER
  username: sa
  password: sa
  driverClassName: org.h2.Driver  
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  generate-ddl: true
  hibernate:
   ddl-auto: update
 mvc:
   format:
     date-time: yyyy-MM-dd HH:mm:ss